/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

//Learn-in-depth
//Keroles Shenouda
//Mastering_Embedded System online diploma
typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// GPIO registers
#define GPIOA_BASE 0x40010800
#define GPIOB_BASE 0x40010C00

#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)
//
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)
//Clock Registers
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
void Clock_Init()
{
	RCC_APB2ENR |= (1<<2); //Enable Clock For GPIOA
	RCC_APB2ENR |= (1<<3); //Enable Clock For GPIOB
}
void GPIOs_Init()
{
	//By default any pin is configured as Floating input but we will make sure
	GPIOA_CRL = (GPIOA_CRL & 0xFFFFFF0F) | (0b0100 << 4); //Set PA1 as Floating input
	GPIOA_CRH = (GPIOA_CRL & 0xFF0FFFFF) | (0b0100 << 20); //Set PA13 as Floating input
	//Output Pins Configuration (PB1,PB13)
	GPIOB_CRL = (GPIOA_CRL & 0xFFFFFF0F) | (0b0001 << 4); //Set PB1 as Push-Pull output pin
	GPIOB_CRH = (GPIOA_CRL & 0xFF0FFFFF) | (0b0101 << 20); //Set PB13 as Open-Drain output
	//Leds is connected to the output pins PB1,PB13
    GPIOB_ODR |= (1<<1); //turn off led intially
    GPIOB_ODR |= (1<<13); //turn off led intially
}
void wait (uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++)
	{
		for(j=0;j<255;j++);
	}
}
int main(void)
{
	Clock_Init();
	GPIOs_Init();

	while(1)
	{
		if(((GPIOA_IDR & (1<<1))>>1)==0) //if switch pressed
		{
			GPIOB_ODR ^= (1<<1); //Toggle led PB1
			while((GPIOA_IDR & (1<<1))==0); //Single pressing mode
		}
		if((GPIOA_IDR & (1<<13))!=0) //if switch pressed
		{
			GPIOB_ODR ^= (1<<13); //Toggle led PB13
		}
		wait(1);
	}
}
