## Prepared by Fawzy Bashandy

# Compiler and machine Specific
CC = gcc.exe
CFLAGS =
INCS = -I inc/.
LIBS =

# Directories
SRCDIR = src
OBJDIR = obj
BINDIR = bin

# Source files and object files
SRC = $(wildcard $(SRCDIR)/*.c)
OBJ = $(patsubst $(SRCDIR)/%.c, $(OBJDIR)/%.o, $(SRC))
AS = $(wildcard *.s)
ASOBJ = $(patsubst %.s, $(OBJDIR)/%.o, $(AS))

# Executable name
EXECUTABLE = $(BINDIR)/Student_Management_System.exe

# Phony targets
.PHONY: all clean cleanAll run

# Default target
all: $(EXECUTABLE)
	@echo "======== Project is built successfully ========"

# Linking target
$(EXECUTABLE): $(OBJ) $(ASOBJ)
	$(CC) $(LIBS) $^ -o $@

# Compile C source files
$(OBJDIR)/%.o: $(SRCDIR)/%.c
	$(CC) -c $(CFLAGS) $(INCS) $< -o $@

# Assemble assembly source files
$(OBJDIR)/%.o: %.s
	$(CC) -c $(CFLAGS) $(INCS) $< -o $@

# Clean targets
clean:
	rm -f $(BINDIR)/*.exe

cleanAll: clean
	rm -f $(OBJDIR)/*.o

# Run target
run:
	$(EXECUTABLE)